# Numpy Learning File

## _Numpy Arrays_

In [7]:
import numpy as np

In [13]:
# Creating a 1D array
list_ = [1, 2, 3, 4, 5]



In [15]:
# Converting the list to a NumPy array
array_1d = np.array(list_)
array_1d

array([1, 2, 3, 4, 5])

In [21]:
# Creating a 2D array
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(list_2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<hr>

### Creating with `arange()`

The arguments of `arange()` are:

- **start**: Start of the interval range  
- **stop**: End of the interval range  
- **step**: Step size of the interval  
- **dtype**: (Optional) Type of the output array



In [40]:
array_1d = np.arange(1, 10)
array_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<hr>

### Using `zeros()` to Create an Array of Zeros

The arguments of `zeros()` are:

- **shape**: Dimensions of the array  
- **dtype**: (Optional) Type of the output array



In [47]:
array_zeros = np.zeros((3, 3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<hr>

### Using `ones()` to Create an Array of Ones

The arguments of `ones()` are:

- **shape**: Dimensions of the array  
- **dtype**: (Optional) Type of the output array



In [51]:
array_ones = np.ones((3, 3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

<hr>

### Using `linspace()` to Create an Array of Evenly Spaced Values

The arguments of `linspace()` are:

- **start**: Start of the interval range  
- **stop**: End of the interval range  
- **num**: Number of samples to generate  
- **endpoint**: If `True`, `stop` is included as the last sample  
- **dtype**: (Optional) Type of the output array


In [56]:
array_linspace = np.linspace(0, 5, 10)
array_linspace

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

<hr>

### Using `eye()` to Create an Identity Matrix

The argument of `eye()` is:

- **n**: Number of rows (or columns) in the output matrix


In [59]:
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<hr>

### Using `random.rand()` to Create an Array of Random Values

The arguments of `random.rand()` are:

- **shape**: Dimensions of the array  
- **dtype**: (Optional) Type of the output array  

By default, it creates a one-dimensional array if no shape is specified.


In [62]:
array_random = np.random.rand(3)
array_random

array([0.04532242, 0.83135375, 0.73552283])

In [64]:
#two-dimensional array
array_random = np.random.rand(3, 3)
array_random

array([[0.87968551, 0.39248866, 0.43644333],
       [0.70917888, 0.78228718, 0.0274481 ],
       [0.85660734, 0.25176393, 0.49976655]])

<hr>

### Using `random.randn()` to Create an Array of Random Values from the Standard Normal Distribution

The arguments of `random.randn()` are:

- **shape**: Dimensions of the array  
- **dtype**: (Optional) Type of the output array  

By default, it creates a one-dimensional array if no shape is specified.


In [69]:
array_random = np.random.randn(3)
array_random

array([ 1.91215618, -0.32460426, -0.3785016 ])

In [71]:
#two-dimensional array
array_random = np.random.randn(3, 3)
array_random

array([[ 0.29928461, -0.65721885,  1.41964911],
       [ 1.12648015, -0.27379548,  0.19090372],
       [-0.84586659,  1.48295756, -0.38812803]])

<hr>

### Using `random.randint()` to Create an Array of Random Integers

The arguments of `random.randint()` are:

- **low**: Lower bound of the interval range  
- **high**: Upper bound of the interval range  
- **size**: Dimensions of the array  
- **dtype**: (Optional) Type of the output array  

By default, it creates a one-dimensional array if no size is specified.


In [77]:
array_random = np.random.randint(1, 10, 5)
array_random

array([5, 7, 3, 5, 2])

In [79]:
#two-dimensional array
array_random = np.random.randint(1, 10, (3, 3))
array_random

array([[3, 5, 3],
       [3, 6, 3],
       [9, 9, 5]])

<hr>

### Using `reshape()` to Change the Dimensions of an Array

The argument of `reshape()` is:

- **newshape**: New dimensions of the array

In [82]:
array_1d = np.arange(1, 10)
array_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
array_2d = array_1d.reshape(3, 3)
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---
### Using `max()` to Find the Maximum Value in an Array

The argument of `max()` is:

- **axis**: (Optional) Axis along which the maximum value is computed

---

### Using `min()` to Find the Minimum Value in an Array

The argument of `min()` is:

- **axis**: (Optional) Axis along which the minimum value is computed


In [94]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
#maximum value in the entire array
max_value = np.max(array_2d)
max_value

9

In [100]:
#maximum value along each column
max_value = np.max(array_2d, axis=0)
max_value

array([7, 8, 9])

In [102]:
#maximum value along each row
max_value = np.max(array_2d, axis=1)
max_value

array([3, 6, 9])

- minimum value in the entire array is the same as above but with min() function

---
### Using `argmax()` to Find the Index of the Maximum Value in an Array

The argument of `argmax()` is:

- **axis**: (Optional) Axis along which the index of the maximum value is computed

---

### Using `argmin()` to Find the Index of the Minimum Value in an Array

The argument of `argmin()` is:

- **axis**: (Optional) Axis along which the index of the minimum value is computed


In [109]:
array_1d = np.array([1, 2, 3, 4, 5])
array_1d

array([1, 2, 3, 4, 5])

In [111]:
max_index = np.argmax(array_1d)
max_index

4

- index of the minimum value is the same as above but with argmin() function


---
### Using `shape()` to Get the Dimensions of an Array

The arguments of `shape()` are:

- **None**


In [129]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
dimensions = array_2d.shape
dimensions

(3, 3)

---
### Using `dtype()` to Get the Data Type of an Array

The arguments of `dtype()` are:

- **None**


In [141]:
array_1d = np.array([1, 2, 3, 4, 5])
array_1d

array([1, 2, 3, 4, 5])

In [143]:
data_type = array_1d.dtype
data_type

dtype('int32')

---
### Array Indexing and Slicing in NumPy

Explanation:

- Indexing is used to access individual elements in an array.
- Slicing is used to access a range of elements or subarrays.
- You can update elements or ranges of elements through indexing and slicing.
- Creating a copy using `copy()` ensures modifications to the slice do not affect the original array.


In [149]:
arr = np.arange(0, 11)
print(arr)
element = arr[0]
element

[ 0  1  2  3  4  5  6  7  8  9 10]


0

In [157]:
#accessing a range of elements
range_elements = arr[1:5]
range_elements

array([1, 2, 3, 4])

In [155]:
#updating an element
arr[0] = 100
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [159]:
arr[1:5] = 200
arr

array([100, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [161]:
#slicing an array
slice_array = arr[0:5]
#slicing an array and updating the slice
slice_array[:] = 300
slice_array


array([300, 300, 300, 300, 300])

In [168]:
#the original array is updated as well since the slice is a view of the original array
arr

array([300, 300, 300, 300, 300,   5,   6,   7,   8,   9,  10])

In [174]:
#creating a copy of an array
arr = np.arange(0,11)
array_copy = arr.copy()
array_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#slicing effect on the original array and the copy array is different because of the copy() function used to create the copy array
#slicing an array and updating the slice in the copy array does not affect the original array 
#slicing an array and updating the slice in the original array affects the copy array as well because the copy array is a view of the original array

---
### Slicing a 2D Array

Explanation:

- Indexing a 2D array can be done using two methods: `array[row][col]` or `array[row, col]`.
- Slicing can extract rows, columns, or subarrays.


In [176]:
array_4d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_4d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [178]:
#accessing an element
# first method 
element = array_2d[0][0]
element

1

In [180]:
# second method
element = array_2d[0, 0]
element

1

In [184]:
#accessing a row or a column of elements (subarray)
#accessing a row
row = array_4d[0]
row

array([1, 2, 3])

In [186]:
#accessing a column
column = array_2d[:, 0]
column

array([1, 4, 7])

In [188]:
#accessing a subarray
subarray = array_2d[:2, 1:]
subarray

array([[2, 3],
       [5, 6]])

---
### Using Conditional Selection to Filter Elements in an Array

Explanation:

- Conditional selection allows you to create filters based on conditions (e.g., greater than, less than).
- This feature is powerful for filtering data without loops.


In [195]:
#creating an array
array_ = np.arange(0, 11)
array_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [201]:
#filtering elements greater than 5
filtered_array = array_[array_ > 5]
filtered_array

array([ 6,  7,  8,  9, 10])

In [203]:
#filtering elements less than or equal to 5
filtered_array_1 = array_[array_ <= 5]
filtered_array_1

array([0, 1, 2, 3, 4, 5])

In [207]:
array_ > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [213]:
#filtering elements based on multiple conditions
res = array_[array_> 5]
res

array([ 6,  7,  8,  9, 10])